---
name: CI

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/uneeq-oss/prometheus-mixin-ci:latest
      options: --user root  # HACK GHA lack of repo mounting -> perm issues

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Build/Render jsonnet
        run: make build

      - name: Archive manifests for testing and publishing
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: manifests
          path: manifests/

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Download rendered manifests
        uses: actions/download-artifact@cbed621e49e4c01b044d60f6c80ea4ed6328b281 # v2.1.1
        with:
          name: manifests
          path: manifests/

      - name: Test
        uses: docker://ghcr.io/uneeq-oss/prometheus-mixin-ci:latest@sha256:9bc21d360edd9c77191664a0f6ac977811bf609e5658b0ca744a2e478c1db4b8
        with:
          entrypoint: make
          args: test SKIP_DOCKER=true

  release:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Extract tag
        id: extract_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Extract repository
        id: extract_repo
        run: echo ::set-output name=REPO::${GITHUB_REPOSITORY##*/}

      - name: Download rendered manifests
        uses: actions/download-artifact@cbed621e49e4c01b044d60f6c80ea4ed6328b281 # v2.1.1
        with:
          name: manifests
          path: manifests/

      - name: Package files for upload
        run: |
          tar -cvzf \
            ${{ steps.extract_repo.outputs.REPO }}-rendered-${{ steps.extract_tag.outputs.TAG }}.tar.gz \
            manifests/ \
            LICENSE \
            podmonitor.yaml

      - name: Generate changelog
        id: generate_changelog
        uses: metcalfc/changelog-generator@e5306b306fa2e34f05258789e0e5c526c1bd4352 # v1.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            ${{ steps.generate_changelog.outputs.changelog }}
          files: ${{ steps.extract_repo.outputs.REPO }}-rendered-${{ steps.extract_tag.outputs.TAG }}.tar.gz
